server:
  port: 8081
  
spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/studynote?characterEncoding=utf8
    username: StudyNote
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
